### ISSUE TITLE
octopus + rspec mocks result in test failures

### ISSUE THREAD

**Issue by blythedunham** [thiagopradi/octopus#116]
Rspec raises error RSpec::Rails::IllegalDataAccessException ("stubbed models are not allowed to access the database") for mocks when ActiveRecord#connection is called from set_connection_on_association 

rescuing the error fixes it, but perhaps it is preferable to check if octopus is enabled before calling self.connection.respond_to?(:current_shard) or before adding the callbacks in the first place. If I have time later, I can make a pull request

```
def set_connection_on_association
  return unless ::Octopus.enabled?
```

**Comment by fuJiin** [comment]
Hey guys, I'm still having issues with Octopus and RSpec.  When I try running a controller or request spec on an endpoint that uses `using(:slave_follower)`, I always get an object not found error.  If I run an ActiveRecord query on the object count, it always shows 0, though I've created at object earlier in the test.  Removing the `using(:slave_follower)` clause fixes it.

Here's the trace:
```
Couldn't find User with id=2

/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.0.2/lib/active_record/relation/finder_methods.rb:198:in `raise_record_not_found_exception!'
/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.0.2/lib/active_record/relation/finder_methods.rb:284:in `find_one'
/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.0.2/lib/active_record/relation/finder_methods.rb:268:in `find_with_ids'
/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.0.2/lib/active_record/relation/finder_methods.rb:35:in `find'
/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-deprecated_finders-1.0.3/lib/active_record/deprecated_finders/relation.rb:122:in `find'
/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.0.2/lib/active_record/querying.rb:3:in `find'
/.rvm/gems/ruby-2.0.0-p481/gems/ar-octopus-0.8.4/lib/octopus/scope_proxy.rb:36:in `block in method_missing'
/.rvm/gems/ruby-2.0.0-p481/gems/ar-octopus-0.8.4/lib/octopus/proxy.rb:223:in `block (2 levels) in run_queries_on_shard'
/.rvm/gems/ruby-2.0.0-p481/gems/ar-octopus-0.8.4/lib/octopus/proxy.rb:429:in `using_shard'
/.rvm/gems/ruby-2.0.0-p481/gems/ar-octopus-0.8.4/lib/octopus/proxy.rb:222:in `block in run_queries_on_shard'
/.rvm/gems/ruby-2.0.0-p481/gems/ar-octopus-0.8.4/lib/octopus/proxy.rb:417:in `keeping_connection_proxy'
/.rvm/gems/ruby-2.0.0-p481/gems/ar-octopus-0.8.4/lib/octopus/proxy.rb:221:in `run_queries_on_shard'
/.rvm/gems/ruby-2.0.0-p481/gems/ar-octopus-0.8.4/lib/octopus/shard_tracking.rb:30:in `run_on_shard'
/.rvm/gems/ruby-2.0.0-p481/gems/ar-octopus-0.8.4/lib/octopus/scope_proxy.rb:36:in `method_missing'
/<redacted>/app/controllers/users_controller.rb:512:in `block in suggestions'
/<redacted>/app/models/application_controller_module.rb:13:in `with_json_render'
/<redacted>/app/controllers/users_controller.rb:511:in `suggestions'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/abstract_controller/base.rb:189:in `process_action'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:373:in `_run__849925857981723301__process_action__callbacks'
/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:80:in `run_callbacks'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/abstract_controller/callbacks.rb:17:in `process_action'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.0.2/lib/active_support/notifications.rb:159:in `block in instrument'
/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.0.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.0.2/lib/active_support/notifications.rb:159:in `instrument'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.0.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/abstract_controller/base.rb:136:in `process'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/abstract_controller/rendering.rb:44:in `process'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_controller/metal.rb:195:in `dispatch'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_controller/metal.rb:231:in `block in action'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:80:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:48:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/journey/router.rb:71:in `block in call'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/journey/router.rb:59:in `each'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/journey/router.rb:59:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:680:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
/.rvm/gems/ruby-2.0.0-p481/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.0.2/lib/active_record/query_cache.rb:36:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:373:in `_run__2012714275934637009__call__callbacks'
/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:80:in `run_callbacks'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/airbrake-3.1.17/lib/airbrake/rails/middleware.rb:13:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.0.2/lib/rails/rack/logger.rb:38:in `call_app'
/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `block in call'
/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `block in tagged'
/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:25:in `tagged'
/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `tagged'
/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.0.2/lib/rails/rack/logger.rb:20:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.0.2/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/middleware/static.rb:64:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/airbrake-3.1.17/lib/airbrake/user_informer.rb:16:in `_call'
/.rvm/gems/ruby-2.0.0-p481/gems/airbrake-3.1.17/lib/airbrake/user_informer.rb:12:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.0.2/lib/rails/engine.rb:511:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.0.2/lib/rails/application.rb:97:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
/.rvm/gems/ruby-2.0.0-p481/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
/.rvm/gems/ruby-2.0.0-p481/gems/rack-test-0.6.3/lib/rack/test.rb:124:in `request'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/testing/integration.rb:311:in `process'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/testing/integration.rb:32:in `get'
/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.0.2/lib/action_dispatch/testing/integration.rb:345:in `block (2 levels) in <module:Runner>'
/<redacted>/spec/requests/users_controller_spec.rb:32:in `block (5 levels) in <top (required)>'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:152:in `instance_exec'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:152:in `block in run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-rails-3.1.0/lib/rspec/rails/adapters.rb:72:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:380:in `execute_with'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:446:in `block (2 levels) in run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:447:in `run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:500:in `run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:331:in `with_around_example_hooks'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:149:in `run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:490:in `block in run_examples'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `map'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `run_examples'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:453:in `run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `block in run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `map'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `block in run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `map'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `block in run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `map'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block (2 levels) in run_specs'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `map'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block in run_specs'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/reporter.rb:53:in `report'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:107:in `run_specs'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:85:in `run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
/.rvm/gems/ruby-2.0.0-p481/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
/.rvm/gems/ruby-2.0.0-p481/bin/rspec:23:in `load'
/.rvm/gems/ruby-2.0.0-p481/bin/rspec:23:in `<main>'
/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
```
