### ISSUE TITLE
NoMethodError: undefined method `connection_proxy' (with a possible fix?)

### ISSUE THREAD

**Issue by oogali** [thiagopradi/octopus#332]
I'm using Octopus with Sinatra and ActiveRecord, but I'm getting undefined method exceptions when I try to call ```#using```.

```
[1] pry(main)> SomeModule::Models::Stuff.find(1).using(slave_group: :local_slaves)
D, [2015-09-13T09:42:51.135598 #52467] DEBUG -- :   SomeModule::Models::Offer Load (0.4ms)  SELECT  "stuff".* FROM "stuff" WHERE "stuff"."id" = $1 LIMIT 1  [["id", 1]]
NoMethodError: undefined method `connection_proxy' for #<SomeModule::Models::Stuff:0xdeadbeef>
from /Users/oogali/project/vendor/gems/activemodel-4.2.0/lib/active_model/attribute_methods.rb:433:in `method_missing'
```

If I call ```connection_proxy``` directly, it appears that it's working.

```
[1] pry(main)> ActiveRecord::Base.connection_proxy
=> #<Octopus::Proxy:0x007f958c2e67f0
 @adapters=#<Set: {}>,
 @config={:adapter=>"postgresql", :database=>"project", :host=>"localhost", :username=>"<redacted>", :password=>"<redacted>", :pool=>5},
 @entire_sharded=nil,
 @groups={},
 @shards=
  {"master"=>
...
```

Same thing with my model class, if I call ```connection_proxy``` against that it's fine, but it fails whenever I try to perform an actual query.

Here's a backtrace:
```
[8] pry(main)> _ex_.backtrace
=> ["/Users/oogali/project/gems/gems/activemodel-4.2.0/lib/active_model/attribute_methods.rb:433:in `method_missing'",
 "/Users/oogali/project/gems/bundler/gems/octopus-b93e949b7917/lib/octopus/model.rb:13:in `clean_table_name'",
 "/Users/oogali/project/gems/bundler/gems/octopus-b93e949b7917/lib/octopus/model.rb:25:in `using'",
 "(pry):4:in `__pry__'",
 "/Users/oogali/project/gems/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `eval'",
 "/Users/oogali/project/gems/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `evaluate_ruby'",
...
<deleted the rest of the backtrace that is specific to pry>
```
However, in my fork I modified ```Octopus::Model::SharedMethods#clean_table_name``` to call ```self.class.connection_proxy``` (instead of just 'connection_proxy'), and everything is now working for me.

Could it really be that simple?

**Comment by oogali** [comment]
Nope, not that simple.

I currently have the following in place to get it working in Pry (which for me, needs self.class.connection_proxy) and in app (which needs connection_proxy):

```
diff --git a/lib/octopus/model.rb b/lib/octopus/model.rb
index f450884..2c60743 100644
--- a/lib/octopus/model.rb
+++ b/lib/octopus/model.rb
@@ -10,7 +10,7 @@ module Octopus

     module SharedMethods
       def clean_table_name
-        return unless connection_proxy.should_clean_table_name?
+        return unless (self.respond_to?(:connection_proxy) ? connection_proxy : self.class.connection_proxy).should_clean_table_name?

         if self != ActiveRecord::Base && self.respond_to?(:reset_table_name) && !custom_octopus_table_name
           reset_table_name
```

**Comment by anhkind** [comment]
I think the correct usage should be

```
SomeModule::Models::Stuff.using(slave_group: :local_slaves).find(1)
```
