### ISSUE TITLE
migrating using ipaddress

### ISSUE THREAD

**Issue by warp-linden** [thiagopradi/octopus#365]
why is it migrating using an ipaddress. this complicates local development as you have to configured mysql to allow remote connections.  Any suggestions?

```
  Mysql2::Error: CREATE command denied to user 'user'@'10.xx.xx.xx' for table 'schema_migrations':   CREATE TABLE `schema_migrations` (`version` varchar(255) NOT NULL) ENGINE=InnoDB
  vendor/ruby/1.9.1/gems/activerecord-  3.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'
  xxx/vendor/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
```

**Comment by warp-linden** [comment]
this was not the issue.. the issue is it was trying to migrate all databases and one of the db's is not meant to be migrated. :(  Solved in my other ticket
