### ISSUE TITLE
NoMethodError: protected method `find_nth' called for #<ActiveRecord::AssociationRelation []>

### ISSUE THREAD

**Issue by biscar** [thiagopradi/octopus#367]
I am using octopus 0.8.6

When I call method **first!** on AssociationRelation I get this exception "NoMethodError: protected method `find_nth' called for ActiveRecord::AssociationRelation []"

@nickmarden,  @paulczajka, @sobrinho  I think this related with #352.

This can be reproduced in octopus spec when **first**  replaced by **first!**:

spec/octopus/association_shard_tracking_spec.rb
```
 it 'find' do
     expect(@brazil_client.comments.first!).to eq(@comment_brazil)
     @brazil_client.comments.destroy_all
     expect(@brazil_client.comments.first!).to be_nil
 end
```
Backtrace:
```
NoMethodError: protected method `find_nth' called for #<ActiveRecord::AssociationRelation []>
/home/vital/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:136:in `method_missing'
/home/vital/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:99:in `method_missing'
./lib/octopus/relation_proxy.rb:23:in `public_send'
./lib/octopus/relation_proxy.rb:23:in `block in method_missing'
./lib/octopus/proxy.rb:246:in `block (2 levels) in run_queries_on_shard'
./lib/octopus/proxy.rb:509:in `using_shard'
./lib/octopus/proxy.rb:245:in `block in run_queries_on_shard'
./lib/octopus/proxy.rb:492:in `keeping_connection_proxy'
./lib/octopus/proxy.rb:244:in `run_queries_on_shard'
./lib/octopus/shard_tracking.rb:30:in `run_on_shard'
./lib/octopus/relation_proxy.rb:23:in `method_missing'
/home/vital/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.6/lib/active_record/associations/collection_proxy.rb:32:in `find_nth'
/home/vital/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:489:in `find_nth!'
/home/vital/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:134:in `first!'
./lib/octopus/relation_proxy.rb:23:in `public_send'
./lib/octopus/relation_proxy.rb:23:in `block in method_missing'
./lib/octopus/proxy.rb:246:in `block (2 levels) in run_queries_on_shard'
./lib/octopus/proxy.rb:509:in `using_shard'
./lib/octopus/proxy.rb:245:in `block in run_queries_on_shard'
./lib/octopus/proxy.rb:492:in `keeping_connection_proxy'
./lib/octopus/proxy.rb:244:in `run_queries_on_shard'
./lib/octopus/shard_tracking.rb:30:in `run_on_shard'
./lib/octopus/relation_proxy.rb:23:in `method_missing'
./spec/octopus/association_shard_tracking_spec.rb:685:in `block (4 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'

```

**Comment by thiagopradi** [comment]
Thanks for reporting! fixed by https://github.com/thiagopradi/octopus/commit/e60f90df1b75f782d0632ca39f0fd4cd16396857.
