### ISSUE TITLE
When pass a object to sidekiq ,The job process will raise a exception

### ISSUE THREAD

**Issue by tomorrownull** [thiagopradi/octopus#485]
The environment

ruby 2.3.0
rails 5.0.1

Call like this

Service.delay.invokeAMethod(Record.first)

error
***********************************************
WARN: NoMethodError: undefined method `delegate_hash' for #<Hash:0x00000008120f18>
Did you mean?  delete_if
/ar-octopus-0.9.2/lib/octopus/model.rb:57:in `init_with'
ruby-2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:382:in `init_with'

**Comment by joeyschoblaska** [comment]
This should be fixed by https://github.com/thiagopradi/octopus/pull/522

**Comment by joonty** [comment]
That PR was closed instead of merged, was that deliberate? Is there another fix for this?

**Comment by joeyschoblaska** [comment]
I haven't looked at this issue since I opened my PR. I closed it because this project is in maintenance mode with the release of Rails 6 and it seemed unlikely to get merged.
