### ISSUE TITLE
Using Phusion Passenger / Forking on Rails 5.2: NoMethodError (undefined method `any?' for nil:NilClass)

### ISSUE THREAD

**Issue by erkie** [thiagopradi/octopus#489]
While trying to deploy [our fork](https://github.com/thiagopradi/octopus/pull/488) we got another error message when deploying to Phusion Passenger.

```
NoMethodError (undefined method `any?' for nil:NilClass):

activerecord (5.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `block in connected?'
/Users/erik/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
activerecord (5.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `connected?'
/Users/erik/feederco/octopus/lib/octopus/proxy.rb:165:in `block in connected?'
/Users/erik/feederco/octopus/lib/octopus/proxy.rb:165:in `any?'
/Users/erik/feederco/octopus/lib/octopus/proxy.rb:165:in `connected?'
/Users/erik/feederco/octopus/lib/octopus/model.rb:202:in `connected_with_octopus?'
activerecord (5.2.0) lib/active_record/railtie.rb:163:in `block (3 levels) in <class:Railtie>'
```

This could easiliy be replicated locally by downloading and running [Passenger Standalone](https://www.phusionpassenger.com/library/config/standalone/intro.html)

```
passenger start --port 3001
```

It seems to be related to this commit:

https://github.com/rails/rails/commit/f32cff5563f2188e657aa2fd9f8513f0da4a49ca#diff-7735c67f539e7d1e2908a4d5d8909c24R453

From what I can read from there it seems that it is no longer safe to use `ConnectionPool` after it has been discarded.

**Comment by erkie** [comment]
Hi, sorry! We moved to [Knockoff](https://github.com/joinhandshake/knockoff) briefly after I made this issue, but I still think the steps should work by using `passenger start --port 3001`

**Comment by jhoareau** [comment]
I'm experiencing the same issue as @whitmer with the latest version of the gem (0.10.1) and Rails 5.2, using Puma forked workers. I've written a terrible money-patch hack/workaround that seems to do the trick on most requests except some edge cases on non-preheated workers : 
```ruby
module Octopus
  class Proxy
    alias_method :safe_connection_without_fork_check, :safe_connection

    def safe_connection_with_fork_check(connection_pool)
      safe_connection_without_fork_check(connection_pool)
    rescue NoMethodError
      proxy_config.reinitialize_shards
      retry
    end

    alias_method :safe_connection, :safe_connection_with_fork_check

    def connected?
      shards.any? { |_k, v| v.connected? }
    rescue NoMethodError
      proxy_config.reinitialize_shards
      retry
    end
  end
end
```

**Comment by jhoareau** [comment]
And in order to fix the early cases for non-preheated workers (only applies to Puma, I don't know about other web server gems), in the puma initializer:
```
on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    Octopus::Proxy.proxy_config.reinitialize_shards
  end
```

**Comment by kjvarga** [comment]
@jhoareau I've been running with the Octopus work around you mentioned above and it was pretty good.  But my Sidekiq worker nodes sometimes become unresponsive and out of memory.  So I tried your Puma `on_worker_boot` work around but started receiving `RuntimeError: Nonexistent Shard Name: master` errors from my endpoints (and the workers - sometimes).  I don't think our code is at fault because we don't refer explicitly to the master shard (I've read about string/symbol issues for the shard names).  But now I can't find your Puma workaround - has the comment been deleted?

**Comment by sagar18041** [comment]
Similar issue with Unicorn on production environment:
`NoMethodError (undefined method `any?' for nil:NilClass):
F, [2019-02-07T09:54:30.989707 #5893] FATAL -- :    
F, [2019-02-07T09:54:30.989764 #5893] FATAL -- :  activerecord (5.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:423:in `block in connected?'
 /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
 activerecord (5.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:423:in `connected?'
 ar-octopus (0.10.1) lib/octopus/proxy.rb:173:in `block in connected?'
 ar-octopus (0.10.1) lib/octopus/proxy.rb:173:in `any?'
 ar-octopus (0.10.1) lib/octopus/proxy.rb:173:in `connected?'
 ar-octopus (0.10.1) lib/octopus/model.rb:194:in `connected_with_octopus?'
 activerecord (5.2.2) lib/active_record/railties/controller_runtime.rb:42:in `append_info_to_payload'
 actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:38:in `ensure in block in process_action'
 actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:38:in `block in process_action'
 activesupport (5.2.2) lib/active_support/notifications.rb:168:in `block in instrument'
 activesupport (5.2.2) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
 activesupport (5.2.2) lib/active_support/notifications.rb:168:in `instrument'
 actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
 actionpack (5.2.2) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
 searchkick (3.1.2) lib/searchkick/logging.rb:209:in `process_action'
 activerecord (5.2.2) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
 actionpack (5.2.2) lib/abstract_controller/base.rb:134:in `process'
 actionpack (5.2.2) lib/action_controller/metal.rb:191:in `dispatch'
 actionpack (5.2.2) lib/action_controller/metal.rb:252:in `dispatch'
 actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
 actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:34:in `serve'
 actionpack (5.2.2) lib/action_dispatch/journey/router.rb:52:in `block in serve'
 actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `each'
 actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `serve'
 actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:840:in `call'
 warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
 warden (1.2.8) lib/warden/manager.rb:34:in `catch'
 warden (1.2.8) lib/warden/manager.rb:34:in `call'
 rack (2.0.6) lib/rack/etag.rb:25:in `call'
 rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
 rack (2.0.6) lib/rack/head.rb:12:in `call'
 actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
 activesupport (5.2.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
 actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
 actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
 railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
 activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
 activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
 activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
 railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
 actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
 actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
 rack (2.0.6) lib/rack/runtime.rb:22:in `call'
 activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
 rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
 rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
 railties (5.2.2) lib/rails/engine.rb:524:in `call'
 unicorn (5.4.1) lib/unicorn/http_server.rb:606:in `process_client'
 unicorn (5.4.1) lib/unicorn/http_server.rb:701:in `worker_loop'
 unicorn (5.4.1) lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
 unicorn (5.4.1) lib/unicorn/http_server.rb:142:in `start'
 unicorn (5.4.1) bin/unicorn:126:in `<top (required)>'
 /usr/local/rvm/gems/ruby-2.5.3@rails_app-service/bin/unicorn:23:in `load'
 /usr/local/rvm/gems/ruby-2.5.3@rails_app-service/bin/unicorn:23:in `<main>'
 /usr/local/rvm/gems/ruby-2.5.3@rails_app-service/bin/ruby_executable_hooks:24:in `eval'
 /usr/local/rvm/gems/ruby-2.5.3@rails_app-service/bin/ruby_executable_hooks:24:in `<main>'
`
Version:
Rails 5.2.2
Ruby 2.5.3
Octopus 0.10.1
Unicorn 5.4.1

**Comment by knagode** [comment]
I am getting this error as well. We are using puma. I noticed that everything works in console (`rails c`).

**Comment by taf2** [comment]
I can say for sure that this error is directly related to mis-configured database connection handling in your puma / unicorn configuration...  Be sure you are correctly disconnect in your before fork and also reconnecting correctly in your after fork.

For example unicorn you need before fork:

```
      ActiveRecord::Base.connection_proxy.clear_all_connections!
      # maybe also any pools
      (ActiveRecord::Base.connection_proxy.instance_variable_get(:@shards) || []).each do |shard, connection_pool|
        connection_pool.disconnect!
      end
```

after fork
```
    Octopus.config['production']['master'] = ActiveRecord::Base.connection.config # maybe needed 
    ActiveRecord::Base.connection.initialize_shards(Octopus.config)
```
